<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Logowanie</title>
</head>
<body>
<form action="" method="post">
  <fieldset>
	<legend>Logowanie</legend>
	<?php
	// dołączamy plik konfiguracyjny oraz skrypt logowania
	require_once 'config.php'; 
	include 'login.php'; 
	?>
	<input type="text" name="user" maxlength="30" placeholder="Login" required autofocus />
	<input type="password" name="password" maxlength="30" placeholder="Hasło" required />
	<button type="submit" name="submit">zaloguj mnie</button>
  </fieldset>
</form>
</body>
</html>